package modelo.enums;

public enum Provincia {
    ALAVA, ALBACETE, ALICANTE, ALMERIA, ASTURIAS, AVILA, BADAJOZ, BALEARES,
    BARCELONA, BURGOS, CACERES, CADIZ, CANTABRIA, CASTELLON, CIUDAD_REAL,
    CORDOBA, CUENCA, GIRONA, GRANADA, GUADALAJARA, GUIPUZCOA, HUELVA,
    HUESCA, JAEN, LEON, LLEIDA, LUGO, MADRID, MALAGA, MURCIA, NAVARRA,
    OURENSE, PALENCIA, LAS_PALMAS, PONTEVEDRA, LA_RIOJA, SALAMANCA,
    SEGOVIA, SEVILLA, SORIA, TARRAGONA, SANTA_CRUZ_DE_TENERIFE, TERUEL,
    TOLEDO, VALENCIA, VALLADOLID, VIZCAYA, ZAMORA, ZARAGOZA, CEUTA, MELILLA
}
